# [START django_app]
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: cc_project.wsgi.application

libraries:
- name: django
  version: "1.2"
